version: '3'
services:
  scaler:
    image: scaler:latest
    command: ["./run.sh"]
    network_mode: "host"
  simulator:
    image: registry.cn-beijing.aliyuncs.com/cloudnative-challenge/simulator:v1.3.3
    network_mode: "host"
    command: function_smoke_test
